---
title: "R Lesson of the Week (LOTW) - Introduction"
author: "Josh M London"
date: "April 23, 2014"
output: html_document
---

## Purpose and Objective

Over the past few years, a number of novice or rare users of R have expressed a desire to learn more about R and, especially, how to use the R programming language to organize, munge and explore data. Too often, users are exposed to the R programming language as a vehicle to learn statistical analysis and not as a vehicle for learning concepts of computer programming, data manipulation and data exploration.

The R Lesson of the Week (R-LOTW) club will attempt to provide novice users exposure and experience using R as data exploration tool. By the end of the journey (52 weeks?), users should be able to 

1) efficiently load a dataset; 
2) organize, edit and join data tables; 
3) calculate summary statistics and perform 'group by' operations; 
4) connect to and query from a database; 
5) generate meaningful and production quality plots for visualizing data; and 
6) produce professional and reproducible reports (using the `knitr` and `rmarkdown` packages)

There are 3 Rules to the R-LOTW Club:

- Rule number 1: You never talk about R-LOTW club
- Rule number 2: You NEVER talk about R-LOTW club
- Rule number 3: If this is your first time at R-LOTW club you will code tonight

## Course Structure

To keep a sensible balance between commitments to this course and other work requirements and our personal lives, the focus of this course will be weekly exercises. Each week, students in the club will receive an email with at least two files. One will contain the lesson(s) for the week and, if written well, should provide a combination of explanatory text and example code that students can follow along and demonstrate for themselves. In addition to the weekly lesson, students will be given a homework assignment that will require the students to apply what they have learned from the lesson and then develop a report using `knitr` and `rmarkdown`.

Lessons will go out on Monday mornings and homework will be due the following Monday at noon (local time).

## Installing R and RStudio

R can be installed from the [CRAN website](http://cran.us.r-project.org/). Windows users working under enterprise security restrictions, should work with their IT staff to install R in a location that allows proper write permissions. For AFSC users, the current best practice is to change the install location/path of R to your 'D' drive or to a specified directory at the root of your C drive (e.g. C:/R). AFSC windows users should NOT install R, RStudio or any of the supporting programs to the 'My Documents' folder. 

OS X and Linux users should be able to install R with typical settings and less headache.

[RStudio (preview release)](http://www.rstudio.com/ide/download/preview) is an Integrated Development Environment (IDE) developed for R. RStudio is cross-platform and should be installed using default settings for all platforms. This provides a more capable software interface for developing R scripts, creating plots, knitr documents, version control, package management, etc. All lessons will presume the use of RStudio as the IDE.

In addition to R and RStudio, you will need to install support for TeX documents in order to create some types of PDF documents. Windows users should download and install [MikTex](http://miktex.org/download) and OS X users should download and install [MacTex](http://tug.org/mactex/downloading.html). It is probably best if you install TeX support prior to installing RStudio as RStudio will auto-detect your TeX install.

Lastly, Windows users will need to install the latest version of [RTools](http://cran.r-project.org/bin/windows/Rtools)

## Installing Packages

R has a wide range of built-in capabilities, however, user contributed packages extend the capabilities even further. Future lessons of the week may require installation of specific packages.

All of these packages are available from [CRAN](http://cran.us.r-project.org/web/packages/available_packages_by_name.html) where you can browse all of the packages available for use within R. One can download and install the packages directly, however, you can also install packages from within R or RStudio. Within RStudio, under the `Tools` menu, select the `Install Packages...` option. Skip this step, for now. We'll come back to it in the `Testing Your Install` section below.

In addition to CRAN, some packages are only available via [GitHub](http://github.com). The `devtools` package is used to install packages from GitHub. The `rmarkdown` package is an example of this. While the preview release of RStudio should install the latest `rmarkdown`, for demonstration purposes, it can be installed with the following code

```{r,rmarkdown-code-block,echo=TRUE,results=FALSE,eval=FALSE}
install.packages("devtools")
devtools::install_github("rstudio/rmarkdown")
```

## Testing Your Install

Once you have R, TeX support, RStudio installed, take a moment to review the [documentation](https://support.rstudio.com/hc/en-us/categories/200035113-Documentation) available on the RStudio website. For now, just focus on the [Using RStudio](https://support.rstudio.com/hc/en-us/sections/200107586-Using-RStudio) section. This will give you a general overview of the options and, hopefully, provide some level of comfort working within RStudio. Don't worry too much about all the various options. As you use it more, you will become more comfortable.

Now, let's fire up RStudio and confirm all of our settings and isntallations went according to plan. First, let's revisit the idea of package installation and head to the `Tools` menu and select the `Install Packages...` option. The tool should be set to install from CRAN and there should be a blank section where you can enter a comma separated list of packages you want to install. Enter `ggplot2, knitr, devtools`, confirm `install dependencies` is checked and click the Install button. 

Once those packages have successfully installed, we'll now try to create a test R-Markdown file and the resulting HTML and PDF files. Within RStudio, go to the File menu, then New File and select R Markdown. This will open up a new script file named `Untitled.Rmd` and it will be pre-filled with basic info as a basic template. To test that you have everything installed correctly, save the file and give it a new name. Then, you'll see a button at the top of the editor window that says `Knit HTML`. Click on that button and you should see some activity in the console window, creation of a .html file and it will open up in a preview window. If this process does not work, you'll need to troubleshoot your installation. Once you have successfully created an HTML file, you can also test creation of PDF by selecting `Knit PDF` from the pull down arrow next to the `Knit HTML` button. If this process does not work, you'll likely need to troubleshoot your TeX installation. Lastly, RStudio has preliminary support for creation of MS Word files. Select `Knit Word` from the same pull down and it should create a Word file version.

## Learning More About R-Markdown

R-markdown will be the format for creating the weekly lessons as well as the format for creating and completing the homework assignments. Given this, I suggest you take some time to learn more about R Markdown as well as the generic markdown format. The [R Markdown website](http://rmarkdown.rstudio.com/) provides a good overview of the capabilities.
